dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "12.2.0"
before_install:
  - cd project
install:
  - npm install
before_script:
  - npm run driver:update
  - npm run driver:start
script:
  - npm run test