dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "12.2.0"
install:
  - npm ci
before_script:
  - npm run driver:update
  - npm run driver:start & sleep 10 
script:
  - npm run test