dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "12.2.0"
install:
  - npm install
script:
  - npm run driver:update
  - npm run driver:start
  - open -a Terminal -n
  - npm run test